// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200630125823_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Domain.Locality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Localities");

                    b.HasData(
                        new
                        {
                            Id = "0100000000",
                            LocalityName = "Title1"
                        },
                        new
                        {
                            Id = "0100100000",
                            Category = 'С',
                            LocalityName = "Child11",
                            ParentId = "0100000000"
                        },
                        new
                        {
                            Id = "0100100100",
                            LocalityName = "Child111",
                            ParentId = "0100100000"
                        },
                        new
                        {
                            Id = "0100200000",
                            Category = 'Щ',
                            LocalityName = "Child12",
                            ParentId = "0100000000"
                        },
                        new
                        {
                            Id = "0200000000",
                            LocalityName = "Title2"
                        },
                        new
                        {
                            Id = "0200100000",
                            Category = 'Т',
                            LocalityName = "Child21",
                            ParentId = "0200000000"
                        },
                        new
                        {
                            Id = "0200200000",
                            Category = 'С',
                            LocalityName = "Child22",
                            ParentId = "0200000000"
                        });
                });

            modelBuilder.Entity("Domain.Locality", b =>
                {
                    b.HasOne("Domain.Locality", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
