// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Locality", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("Category")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Localities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 11L,
                            Category = 'С',
                            ParentId = 1L,
                            Title = "Child11"
                        },
                        new
                        {
                            Id = 111L,
                            ParentId = 11L,
                            Title = "Child111"
                        },
                        new
                        {
                            Id = 12L,
                            Category = 'Щ',
                            ParentId = 1L,
                            Title = "Child12"
                        },
                        new
                        {
                            Id = 2L,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 21L,
                            Category = 'Т',
                            ParentId = 2L,
                            Title = "Child21"
                        },
                        new
                        {
                            Id = 22L,
                            Category = 'С',
                            ParentId = 2L,
                            Title = "Child22"
                        });
                });

            modelBuilder.Entity("Domain.Locality", b =>
                {
                    b.HasOne("Domain.Locality", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
